### ISSUE TITLE
App concept?

### ISSUE THREAD

**Issue by BTBTravis** [redi-js-teachers/js_sprint_2020_final_project_nmustonen#1]
Hey @nmustonen this is the repo for your final project this semester. In this issue I'd like to discuss your final project concept. 

Do you have any ideas?

What features would you be most interested in working on?

**Comment by doneandout** [comment]
Hi Travis, 

i would like to continue building stuff for my photography project.  I have been trying to push it to a new branch but it is heavy with photos.
I actually have already used JS on my website and I am currently checking out some cool special effects to use to make it more interesting.  
 You should be able to see the website soon.

**Comment by MrTim** [comment]
Hey @nmustonen,
Cool that you have a project and would like to continue working on it! 
Could you please describe what is in the website already (which js functionality) and which special effects you want to build?
This is needed so we can understand the scope of what you want to build/adjust.

**Comment by doneandout** [comment]
hi, I am not able to push it here but I have it here https://github.com/nmustonen/redi_js_spring_2020/tree/JS_Niina/JS_Project

**Comment by MrTim** [comment]
@nmustonen you should have an email about invitation for collaboration for this repository. After you accept it you should be able to push your code here. 
Please do it since we will manage all repositories in here.

**Comment by doneandout** [comment]
where do i find the invitation for the repository ? i don see it

**Comment by MrTim** [comment]
@nmustonen , should be in your email with which you register for Github. Check it in spam as well, in case it end up there.

**Comment by doneandout** [comment]
I found the email -thanks! but i still cannot push my work in this repository.  It says I don't have rights to do it. I also tried to create a new branch push my work there and now Git Bash tells that the tree is clean.  What should I do next ?

**Comment by BTBTravis** [comment]
I will take care of moving your existing photography website to this repository. May I have a link to the current repo you track the site in? Not https://github.com/nmustonen/redi_js_spring_2020/tree/JS_Niina/JS_Project but the repo you copied these files from.

**Comment by doneandout** [comment]
I would like to push my work here, as I have made some changes already. I will try again to push it and hopefully it works. in case of issues, I will let you know. Thanks!

**Comment by BTBTravis** [comment]
Please push your changes to your existing repository and send me a link to that repository. I'll handle moving it here.

**Comment by doneandout** [comment]
so  I still cannot push anything on Github, I do not know why and I have spent a lot of time trying to solve this. 

It is clear that I won't get a certification from this JS course, I will still follow through the lessons that we have as I am interested to see what others did,  but will not participate in showing my project (mainly as I didn't learn as what was expected).

**Comment by BTBTravis** [comment]
Hey @nmustonen sorry you are having problems working with Git/Github. You can always message on teams if you need more direct help via video call for example. If you need help with your project let us know. 🤝
